# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long', models.FloatField()),
                ('lat', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='location',
            name='from_location',
        ),
        migrations.RemoveField(
            model_name='location',
            name='to_location',
        ),
        migrations.AddField(
            model_name='location',
            name='froml',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='froml', to='api.GeoLocation'),
        ),
        migrations.AddField(
            model_name='location',
            name='tol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tol', to='api.GeoLocation'),
        ),
    ]
